"""Compare measurable geometry with published fabrication limits, not factory approval."""
from pathlib import Path
import sexpdata as s,json,hashlib,math,collections,datetime
R=Path(__file__).resolve().parents[1];p=R/(R.name+'.kicad_pcb');b=s.load(p.open());C=lambda e,k:next((x for x in e if isinstance(x,list) and x and str(x[0])==k),None)
v=[e for e in b if isinstance(e,list) and e and str(e[0])=='via'];tracks=[e for e in b if isinstance(e,list) and e and str(e[0])=='segment'];via_types=collections.Counter((C(e,'size')[1],C(e,'drill')[1]) for e in v)
gap=min(math.dist(C(a,'at')[1:3],C(z,'at')[1:3])-(C(a,'drill')[1]+C(z,'drill')[1])/2 for i,a in enumerate(v) for z in v[i+1:]);texts=[]
for e in b:
 if isinstance(e,list) and e and str(e[0])=='gr_text' and C(e,'layer')[1] in ['F.SilkS','B.SilkS']:
  f=C(C(e,'effects'),'font');texts.append({'text':e[1],'size_mm':C(f,'size')[1:],'stroke_mm':C(f,'thickness')[1]})
checks={'via_hole_at_least_0p15':all(d>=.15 for _,d in via_types),'via_diameter_minus_hole_at_least_0p15':all(o-d>=.15-1e-8 for o,d in via_types),'via_hole_gap_at_least_0p2':gap>=.2,'traces_at_least_0p10':all(C(t,'width')[1]>=.1 for t in tracks),'visible_board_text_at_least_1mm':all(min(t['size_mm'])>=1 for t in texts),'visible_board_text_stroke_at_least_0p10':all(t['stroke_mm']>=.1 for t in texts)}
d={'status':'geometry_subset_passed_factory_approval_pending' if all(checks.values()) else 'failed','checked_at':datetime.datetime.now(datetime.timezone.utc).isoformat(),'board_sha256':hashlib.sha256(p.read_bytes()).hexdigest(),'source':'https://www.jlc.com/portal/vtechnology.html','scope':'Only listed geometry checks; native DRC separately covers spacing. Not a factory DFM approval. No optical or electrical qualification.','checks':checks,'vias':[{'diameter_mm':o,'hole_mm':h,'count':n,'nominal_board_thickness_to_finished_hole_ratio':1.6/h} for (o,h),n in sorted(via_types.items())],'minimum_via_hole_gap_mm':gap,'visible_board_texts':texts,'factory_questions':['Confirm 288 x 0.15 mm finished vias on 1.6 mm four-layer stackup, compensated drill, plating and quote; do not infer plating aspect ratio from finished hole alone.','Confirm green mask, 1 oz finished external copper and 0.10 mm routing; thicker copper invalidates these published limits.','Confirm SMT rotations, stencil thickness/apertures, exposed-pad solder and supported router depaneling.']}
(R/'fabrication_audit.json').write_text(json.dumps(d,ensure_ascii=False,indent=2));print(json.dumps(d,ensure_ascii=False,indent=2));assert all(checks.values())
